name: Rebase stable-rebased branch

on:
  schedule:
  - cron: "0 1 * * *"

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: clone repo
      run: |
        git clone -b ${{ env.branch }} git@github.com:phytec-labs/${{ env.repository_name }}.git ${{ env.repository_name }}
      env:
        repository_name: elements-vexriscv
        branch: stable-rebased

    - name: rebase to upstream
      run: |
        cd ${{ env.repository_name }}
        git remote add upstream git@github.com:SpinalHDL/VexRiscv.git
        git fetch upstream
        git rebase upstream/master
        cd ../
      env:
        repository_name: elements-vexriscv

    - name: push back to branch
      run: |
        cd ${{ env.repository_name }}
        git push origin HEAD:${{ env.branch }} -f
        cd ../
      env:
        repository_name: elements-vexriscv
        branch: stable-rebased

    - name: post cleanup
      if: always()
      run: |
        rm -rf ${{ env.repository_name }}
      env:
        repository_name: elements-vexriscv
